### ISSUE TITLE
[ERROR] [1724382136.443318]: Error processing request: 'NoneType' object has no attribute 'mus'

### ISSUE THREAD

**Issue by BigWang2025** [mousecpn/RT_ws#1]
Hello, when running the code to move the robotic arm trajectron_node.py, the following error will occur. How should I solve it?

[ERROR] [1724382136.443318]: Error processing request: 'NoneType' object has no attribute 'mus'
['Traceback (most recent call last):\n', '  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_service.py", line 633, in _handle_request\n    response = convert_return_to_response(self.handler(request), self.response_class)\n', '  File "/home/wzx/Code/RT_ws-master/src/trajectron/src/trajectron_node.py", line 385, in score\n    means = pred_dist.mus\n', "AttributeError: 'NoneType' object has no attribute 'mus'\n"]

**Comment by mousecpn** [comment]
Hi, I need more information to help you.
Can you pin a debug point in this line, and print(pred_dist) for me?

**Comment by BigWang2025** [comment]
![3349800f-6ca6-47ec-a407-51350e2e334b](https://github.com/user-attachments/assets/88fa3f3b-43c5-41a5-9db0-77f2daa694cb)
![39f27ecb-9958-4fb8-bc52-71a840c48d0b](https://github.com/user-attachments/assets/cf876c4f-b642-4958-ba98-e9f01361e9b7)

I have the line rospy.loginfo("trajectory_prediction called") in trajectory_prediction, but there is no output

**Comment by BigWang2025** [comment]
Is it because trajectory_prediction is not called correctly?

**Comment by mousecpn** [comment]
It doesn't call trajectory_prediction, it calls trajectory_prediction_asyn.
Can you check whether trajectory_prediction_asyn is called?

**Comment by BigWang2025** [comment]
![40fce3e8-dad8-4f71-8363-1a118cc0f6c6](https://github.com/user-attachments/assets/56716230-5fc1-4b09-ad56-5d51f633934d)
I added this line and still got no output
![9866f9ac-f322-4ce2-a1fe-284371799449](https://github.com/user-attachments/assets/32aea3ea-008d-45f0-b6e5-322acfe6d22e)
Isn't trajectory_prediction called in the main function?

**Comment by mousecpn** [comment]
As what I remember, these three services are outdated.
Now the repo uses a ros message mechanism to call trajectory_prediction_asyn.
![image](https://github.com/user-attachments/assets/6690a44b-750a-40c2-8472-b315de3ae284)

**Comment by BigWang2025** [comment]
Could you please add me on WeChat and give me more details?

**Comment by mousecpn** [comment]
> Could you please add me on WeChat and give me more details?

contact me by email pinhao.song@kuleuven.be

**Comment by BigWang2025** [comment]
![QQ20240823-193856](https://github.com/user-attachments/assets/b1e4b3e8-cc34-47d6-965d-e87efae8984b)
![QQ20240823-193951](https://github.com/user-attachments/assets/b7fadf73-88e3-4725-9ac7-823e4f42708b)
I added a judgment like this. After restarting the computer, running the code again can output normally. Did this run successfully?

**Comment by BigWang2025** [comment]
![QQ20240823-195906](https://github.com/user-attachments/assets/6c92e517-846d-4374-b2bd-73ec6909f20f)
I closed the code and ran it again and it started to report an error again

**Comment by BigWang2025** [comment]
![QQ20240823-195906](https://github.com/user-attachments/assets/f3d7c569-2f62-48c9-98e2-8a07e049ffc5)
Cause of the problem: The terminal input command line running code cannot be completely closed, resulting in the callback function not being called when running again. 
Solution: Use the vscode run and debug buttons to run the code

![371874d7-2e1d-41e8-a923-d30b700b4df0](https://github.com/user-attachments/assets/a1dbcae8-d7cd-4f4d-895f-e59ab3b9e068)
Solution: Make the following changes in the dynamics file
![d90f110d-f1ca-4a76-bac8-0f578d02e4c0](https://github.com/user-attachments/assets/7dab6c3a-a453-430b-bac8-9e521553caac)





> Hello, when running the code to move the robotic arm trajectron_node.py, the following error will occur. How should I solve it?
> 
> [ERROR] [1724382136.443318]: Error processing request: 'NoneType' object has no attribute 'mus' ['Traceback (most recent call last):\n', ' File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_service.py", line 633, in _handle_request\n response = convert_return_to_response(self.handler(request), self.response_class)\n', ' File "/home/wzx/Code/RT_ws-master/src/trajectron/src/trajectron_node.py", line 385, in score\n means = pred_dist.mus\n', "AttributeError: 'NoneType' object has no attribute 'mus'\n"]
